<!DOCTYPE html>
<html data-theme="light" id="important" lang="es">
    <head>
        <meta charset="UTF-8">
        <title><?=_('AppLES')?></title>
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <link rel="stylesheet" href="/css/default.min.css">
    </head>
    <body>
        <?php View::partial('mensajes'); ?>
        <?php View::partial('aside'); ?>
        <main class="container-fluid">
            <?php View::partial('nav'); ?>
            <?php View::content() ?>
            <div class="ajax hide"></div>
            <div class="ajax show"></div>
        </main>
        <script src="/javascript/default.min.js"></script>
    </body>
</html>