<!DOCTYPE html>
<html lang="es">
    <head>
        <meta charset=<?=APP_CHARSET?>>
        <title><?=_('AppLES')?></title>
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <link rel="stylesheet" href="/css/organizadores.min.css">
    </head>
    <body>
        <?php View::partial('mensajes'); ?>
        <main class="container">
            <nav>
                <ul>
                    <li><strong>Organizadores</strong></li>
                    <li><strong>/</strong></li>
                    <li><strong>Eventos</strong></li>
                </ul>
                <ul>
                    <li><?=_('Bienvenido')?> <?=$usuario->apodo?>.</li>
                    <li><a href="/usuarios/salir"><?=_('¿Salir?')?></a></li>
                </ul>
            </nav>
            <?php View::content() ?>
            <div class="ajax hide"></div>
            <div class="ajax show"></div>
        </main>
        <script src="/javascript/organizadores.min.js"></script>
    </body>
</html>