<?php
$tipos = [
	'charla'=>_('Charla'),
	'partida'=>_('Partida'),
];
?>
<article>
    <header>
        <h1><?=$evento->nombre?></h1>
        <br>
    </header>

    <?php if ($evento->imagenes): ?>
        <img src="/img/users/<?=$evento->imagenes?>">
    <?php elseif ($evento->tipo === 'charla'): ?>
        <img src="/img/app/charla.jpg">
    <?php elseif ($evento->tipo === 'partida'): ?>
        <img src="/img/app/partida.jpg">
    <?php endif; ?>

    <section>
        <br>
        <?=nl2br(h($evento->descripcion))?><br>
        <?=Html::tags('/eventos', $evento->etiquetas); ?><br>
        <br>
        <ul>
            <li><b><?=_('Evento')?>:</b> <?=$tipos[$evento->tipo]?></li>
            <li><b><?=_('Sistema')?>:</b> <?=$evento->sistema?></li>
            <li><b><?=_('Organizador')?>:</b> <?=$evento->apodo?></li>
            <li><b><?=_('Participantes mínimo')?>:</b> <?=$evento->participantes_min?></li> 
            <li><b><?=_('Participantes máximo')?>:</b> <?=$evento->participantes_max?></li> 
            <li>
                <b><?=_('Apuntados')?>:</b>
                <?=empty($apuntados[$evento->aid])?0:count($apuntados[$evento->aid]);?>
            </li> 
            <li>
                <b><?=_('Reservas')?>:</b>
                <?=empty($reservas[$evento->aid])?0:count($reservas[$evento->aid]);?>
            </li> 
            <li><b><?=_('Comienza')?>:</b> <?=date('H:i d-m-Y', strtotime($evento->comienza))?></li>
            <li><b><?=_('Termina')?>:</b> <?=date('H:i d-m-Y', strtotime($evento->termina))?></li>
            <li><b><?=_('Aceptada')?>:</b> <?=empty($evento->aceptado)?_('No'):_('Sí')?></li>
        </ul>

        <?php if ($evento->aceptado && $evento->organizador === $usuario->aid): ?>
            <small class="red"><?=_('Editar un evento aceptado lo desactiva hasta que lo revise un moderador.')?></small>
        <?php endif; ?>
    </section>

    <footer class="grid">
        <?php if ( ! $evento->aceptado && $usuario->rol > 2): ?>
            <a role="button" href="/moderadores/eventos/aceptar/<?=$evento->aid?>"><?=_('Aceptar')?></a>
        <?php endif; ?>

        <?php if ($evento->organizador === $usuario->aid): ?>
            <a role="button" data-ajax=".ajax.show" href="/organizadores/eventos/formulario/<?=$evento->aid?>"><?=_('Editar')?></a>
        <?php endif; ?>

        <?php if ($evento->aceptado): ?>
            <?php if ($apuntado): ?>
                <a role="button" href="/participantes/reservas/desapuntarse/<?=$evento->aid?>"><?=_('Desapuntarse')?></a>
            <?php else: ?>
                <a role="button" href="/participantes/reservas/apuntarse/<?=$evento->aid?>"><?=_('Apuntarse')?></a>
            <?php endif; ?>
        <?php endif; ?>
    </footer>
</article>
