
<?=Form::open('participantes/reservas/confirmar', 'post', 'class="modal confirmar_reserva"')?>
    <header>
        <button type="button" class="transparent" data-hide=".modal, .overlay"><img alt="<?=_('Cerrar ventana')?>" src="/img/icons/x.svg"></button>
        <h3><?=_('Apuntados')?></h3>
    </header>
    <br>
    <section>
        <label>
            <?=Form::check('participantes[]', $usuario->aid, null, empty($apuntado[Session::get('aid')])?false:true)?>

            <?=$usuario->apodo?>
        </label>
        <?php foreach($menores as $men): ?>
            <label>
                <?=Form::check('participantes[]', $men->aid, null, empty($apuntado[$men->aid])?false:true)?>
                <?=$men->nombre?>
            </label>
        <?php endforeach; ?>
    </section>
    <br>
    <footer>
        <?=Form::submit('Confirmar', 'name="action" value="confirmar_reserva"')?>
    </footer>
    <?=Form::hidden('eventos_aid', null, $eventos_aid)?>
<?=Form::close()?>

<div class="overlay"></div>
