
<?php if (Session::has('mensajes')): ?>
	<div class="contenedor-de-mensajes">
		<?php
		$mensaje_tiempo = 8;
		foreach (Session::get('mensajes') as $mensaje): ?>
			<div class="mensaje-<?=$mensaje_aid=_str::aid()?>">
				<button type="button" class="transparente" data-eliminar="padre"><img alt="<?=_('Cerrar mensaje')?>" src="/img/icons/x.svg"></button>
				<h3>INFO</h3>
				<p><?=$mensaje?></p>
			</div>
			<script>
			setTimeout("$('.mensaje-<?=$mensaje_aid?>').fadeOut('slow', function(){ $(this).remove() })", <?=$mensaje_tiempo*1000?>);
			</script>
			<?php
			++$mensaje_tiempo;
		endforeach;
		Session::delete('mensajes'); ?>
	</div>
<?php endif; ?>
