<?php
$controller_name = View::getVar('controller_name');
$module_name = View::getVar('module_name');
$usuario = View::getVar('usuario');

$module = empty($module_name) ? '' : "/$module_name";

$modules = [
	'administradores'=>_('Administradores'),
	'moderadores'=>_('Moderadores'),
	'organizadores'=>_('Organizadores'),
	'participantes'=>_('Participantes'),
];

$controllers = [
	'index'=>_('Portada'),
	'eventos'=>_('Eventos'),
	'menores'=>_('Menores'),
	'reservas'=>_('Reservas'),
	'usuarios'=>_('Usuarios'),
];
?>

<nav>
	<ul>
		<li><button type="button" data-show="aside, .overlay.aside"><?=_('Menú')?></button></li>

		<?php /*if ($module_name): ?>
			<li><a role="button" class="outline" href="/<?=$module_name?>"><?=$modules[$module_name]?></a></li>
		<?php endif;*/ ?>

		<li><a role="button" class="outline" href="<?=$module?>/<?=$controller_name?>"><?=$controllers[$controller_name]?></a></li>
	</ul>
	<?php if (Session::get('aid')): ?>
		<ul>
			<li>
				<?=_('Bienvenido')?> <a href="/usuarios/ver/<?=$usuario->aid?>" class="nowrap"><?=$usuario->apodo?></a>
				<br><b>ID:</b> <?=$usuario->id?>
			</li>
			<li><a role="button" class="outline" href="/usuarios/salir"><?=_('¿Salir?')?></a></li>
		</ul>
	<?php else: ?>
		<ul>
			<li><a role="button" href="/usuarios/entrar"><?=_('Entrar')?></a></li>
		</ul>
	<?php endif; ?>
</nav>
